### PR TITLE
refactor(lib): update dependencies, replace deprecated

### PR DESCRIPTION
**Pull request by mihai-ro**
**Work done**
* refactor(dependencies): replace deprecated dependencies. bump versions to latest. replace tslint with eslint. add lint script. 
* ci(babelrc): target node@16. ~resolve corejs deps on entry~. reference plugin-transform-runtime
* style(static code analyser): define eslint and eslint ignore. cleanup prettierrc
* style(misc): fix lint issues in files
* chore(dist): update dist folder with latest build
* chore(dist): update dist with builtins on usage

### CODE REVIEW

**Comment by csandman** [comment]
Thanks for this, I have let this package's maintenance fall behind a bit and you have made a lot of updates that I would have liked to myself.  I will review this when I get a chance and (after tweaking a few things) merge it.

**Comment by csandman** [comment]
Accidental close, reopened

**Comment by mihai-ro** [comment]
@csandman when can we merge this?

**Review by csandman — APPROVED** [review]

**Comment by csandman** [comment]
@mihai-ro After a couple tweaks I merged it.  On a side note, if you want PRs to be merged faster, keeping them smaller and more focused on a specific change makes that more likely.

**Pull request merged**
